# Generated by Django 3.2.7 on 2021-09-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_subtitile_blog_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
