# Generated by Django 3.2.7 on 2021-10-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(default='hello.jpg', upload_to='pic'),
            preserve_default=False,
        ),
    ]
