# Generated by Django 3.2.7 on 2021-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_blogs_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_date',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_month',
            field=models.CharField(default='jan', max_length=100),
            preserve_default=False,
        ),
    ]
